spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  profiles:
    active: local # Comma-separated list of active profiles. Can be overridden by a command line switch.
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-lifetime: 600000
    maximum-pool-size: 10
  mvc:
    throw-exception-if-no-handler-found: true # Whether a "NoHandlerFoundException" should be thrown if no Handler was found to process a request.
  web:
    resources:
      add-mappings: false